### ISSUE TITLE
Form label for text field position on mobile portrait

### ISSUE THREAD

**Issue by pwalm** [MarketplaceUX/marketplace-style-guides#2]
... might look cooler centered?

**Comment by brampitoyo** [comment]
It might! Try it and see? Hopefully, switching from left to center is just a matter of changing a text-align property.

**Comment by mhanratty** [comment]
Are you referring to the labels section here: http://pwalm.github.io/marketplace-style-guides/forms.html

I'd see what the FFOS pattern is for form labels is. Would be nice to be consistent with their pattern.
