### ISSUE TITLE
Style guide uses 'Open Sans' from Google Fonts instead of 'Fira Sans OT'

### ISSUE THREAD

**Issue by ozten** [MarketplaceUX/marketplace-style-guides#3]
The source code for http://pwalm.github.io/marketplace-style-guides/type.html mentions 'Fira Sans OT', but actually imports Open Sans from Google fonts.

Via @pwalm 
We need to do is make Fira a webfont for this site, and add a DL link for those who need the actual files.

You can grab Fira from this page: http://www.mozilla.org/en-US/styleguide/products/firefox-os/typeface/

**Comment by pwalm** [comment]
On it!

**Comment by pwalm** [comment]
Fixed. Added Fira Sans as a webfont.
